version: "3"
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: theusername
      MYSQL_PASSWORD: thepw
      MYSQL_DATABASE: mydb
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    ports:
      - "6379:6379" 
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
    - "db"
    - "redis"
    environment:
      WAIT_HOSTS: db:3306, redis:6379
    
    


